name: OC Version - Build and Deploy to TestFlight

on:
  push:
    branches:
      - main
    paths:
      - 'OC/**'
  pull_request:
    branches:
      - main
    paths:
      - 'OC/**'
  workflow_dispatch:

env:
  XCODE_VERSION: '15.0'
  IOS_DEPLOYMENT_TARGET: '7.0'
  WORKSPACE_PATH: 'OC/PhotoDIY.xcworkspace'
  SCHEME: 'PhotoDIY'

jobs:
  build-and-deploy:
    name: Build OC and Deploy to TestFlight
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install CocoaPods
        run: |
          gem install cocoapods -v 1.15.2
          pod --version

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: OC/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('OC/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pod Dependencies
        run: |
          cd OC
          pod install --repo-update

      - name: Import Code Signing Certificates
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Download Provisioning Profiles
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build Archive
        run: |
          xcodebuild archive \
            -workspace ${{ env.WORKSPACE_PATH }} \
            -scheme ${{ env.SCHEME }} \
            -configuration Release \
            -archivePath ${{ runner.temp }}/PhotoDIY.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
            CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE_NAME }}"

      - name: Export IPA
        run: |
          # Create export options plist
          cat > ${{ runner.temp }}/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${{ secrets.APPLE_TEAM_ID }}</string>
            <key>uploadSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath ${{ runner.temp }}/PhotoDIY.xcarchive \
            -exportPath ${{ runner.temp }}/export \
            -exportOptionsPlist ${{ runner.temp }}/ExportOptions.plist

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          # Create API key file
          mkdir -p ~/private_keys
          echo "$APP_STORE_CONNECT_API_KEY" | base64 --decode > ~/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8

          xcrun altool --upload-app \
            --type ios \
            --file ${{ runner.temp }}/export/*.ipa \
            --apiKey $APP_STORE_CONNECT_API_KEY_ID \
            --apiIssuer $APP_STORE_CONNECT_ISSUER_ID

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PhotoDIY-OC-IPA
          path: ${{ runner.temp }}/export/*.ipa
          retention-days: 30

      - name: Upload Archive Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: PhotoDIY-OC-Archive
          path: ${{ runner.temp }}/PhotoDIY.xcarchive
          retention-days: 7
