name: Swift Version - Build and Deploy to TestFlight

on:
  push:
    branches:
      - swift
    paths:
      - 'Swift/**'
  pull_request:
    branches:
      - swift
    paths:
      - 'Swift/**'
  workflow_dispatch:

env:
  XCODE_VERSION: '15.0'
  IOS_DEPLOYMENT_TARGET: '15.0'
  PROJECT_PATH: 'Swift/Photofy.xcodeproj'
  SCHEME: 'Photofy'

jobs:
  # 注释掉测试任务以加快构建速度和节省资源
  # 如需运行测试，请取消以下注释
  # test:
  #   name: Run Tests
  #   runs-on: macos-14
  #
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #
  #     - name: Select Xcode Version
  #       run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
  #
  #     - name: Show Xcode Version
  #       run: xcodebuild -version
  #
  #     - name: Run Unit Tests
  #       run: |
  #         xcodebuild test \
  #           -project ${{ env.PROJECT_PATH }} \
  #           -scheme ${{ env.SCHEME }} \
  #           -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
  #           -resultBundlePath ${{ runner.temp }}/TestResults.xcresult
  #
  #     - name: Upload Test Results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: Test-Results
  #         path: ${{ runner.temp }}/TestResults.xcresult
  #         retention-days: 7

  build-and-deploy:
    name: Build Swift and Deploy to TestFlight
    runs-on: macos-14
    # needs: test  # 注释掉测试依赖
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Show Swift Version
        run: swift --version

      - name: Setup App Store Connect API Key
        env:
          API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          # Create API key directory
          mkdir -p ~/private_keys

          # Decode and save API key
          echo "$API_KEY_BASE64" | base64 --decode > ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8

          # Set proper permissions
          chmod 600 ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8

      - name: Increment Build Number
        run: |
          cd Swift/Photofy
          BUILD_NUMBER=${{ github.run_number }}

          # Update build number in project
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" Info.plist

          echo "Build number set to: $BUILD_NUMBER"

      - name: Build Archive
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          xcodebuild archive \
            -project ${{ env.PROJECT_PATH }} \
            -scheme ${{ env.SCHEME }} \
            -configuration Release \
            -archivePath ${{ runner.temp }}/Photofy.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_${ASC_KEY_ID}.p8 \
            -authenticationKeyID ${ASC_KEY_ID} \
            -authenticationKeyIssuerID ${ASC_ISSUER_ID}

      - name: Export IPA
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          # Create export options plist
          cat > ${{ runner.temp }}/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
            <key>manageAppVersionAndBuildNumber</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath ${{ runner.temp }}/Photofy.xcarchive \
            -exportPath ${{ runner.temp }}/export \
            -exportOptionsPlist ${{ runner.temp }}/ExportOptions.plist \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_${ASC_KEY_ID}.p8 \
            -authenticationKeyID ${ASC_KEY_ID} \
            -authenticationKeyIssuerID ${ASC_ISSUER_ID}

      - name: Upload to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file ${{ runner.temp }}/export/*.ipa \
            --apiKey ${ASC_KEY_ID} \
            --apiIssuer ${ASC_ISSUER_ID}

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Photofy-Swift-IPA
          path: ${{ runner.temp }}/export/*.ipa
          retention-days: 30

      - name: Upload Archive Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Photofy-Swift-Archive
          path: ${{ runner.temp }}/Photofy.xcarchive
          retention-days: 7

      - name: Upload dSYM for Crash Analytics
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Photofy-dSYMs
          path: ${{ runner.temp }}/Photofy.xcarchive/dSYMs
          retention-days: 90
